name: Build staging artifacts

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build APK for staging
    runs-on: macos-latest
    steps:
      - name: Downloading sources
        uses: actions/checkout@v2
      - name: Installing Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Installing flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.22.5
      - name: Building APK
        run: ./build_android.sh
        env:
          FLAVOR: staging